;;; panda-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from panda.el

(autoload 'panda-queue-build "panda" "\
Queue a build.  If PLAN is not provided, select it interactively.

(fn &optional PLAN)" t)
(autoload 'panda-build-results "panda" "\
Fetch the build results for a branch under PLAN.
If PLAN is not provided, select it interactively.
The amount of builds to retrieve is controlled by 'panda-latest-max'.

(fn &optional PLAN)" t)
(autoload 'panda-create-release "panda" "\
Create a new release from a succesful build." t)
(autoload 'panda-queue-deploy "panda" "\
Queue a deploy.  If PROJECT and ENVIRONMENT are not provided, select them interactively.

(fn &optional PROJECT ENVIRONMENT)" t)
(autoload 'panda-deploy-status "panda" "\
Display a project's deploy status.  If PROJECT is not provided, select it interactively.

(fn &optional PROJECT)" t)
(autoload 'panda-environment-history "panda" "\
Show the history of ENV-ID in a new buffer.  If env-id is not provided, it will be prompted.

(fn &optional ENV-ID)" t)
(register-definition-prefixes "panda" '("panda-"))

;;; End of scraped data

(provide 'panda-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; panda-autoloads.el ends here
