;;; magit-gitlab-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-gitlab.el

 (autoload 'magit-gitlab-mr-edit-description "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-edit-milestone "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-edit-target-branch "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-toggle-draft "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-edit-assignees "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-assign-to-reviewers "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-assign-to-me "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-assign-to-author "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-edit-reviewers "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-review-by-assignees "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-browse "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-browse-kill "magit-gitlab" nil t)
 (autoload 'magit-gitlab-customize-favorites "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr-assign-to-favorite "magit-gitlab" nil t)
 (autoload 'magit-gitlab-mr "magit-gitlab" nil t)
(register-definition-prefixes "magit-gitlab" '("magit-gitlab-"))

;;; End of scraped data

(provide 'magit-gitlab-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-gitlab-autoloads.el ends here
