;;; gnus-select-account-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gnus-select-account.el

(autoload 'gnus-select-account "gnus-select-account" "\
Select an account before writing a mail in gnus." t)
(autoload 'gnus-select-account-enable "gnus-select-account" "\
Enable gnus-select-account feature." t)
(register-definition-prefixes "gnus-select-account" '("gnus-select-account-"))

;;; End of scraped data

(provide 'gnus-select-account-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gnus-select-account-autoloads.el ends here
