;;; vega-view-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vega-view.el

(autoload 'vega-view "vega-view" "\
Convert the preceding sexp (in supported languages) to JSON
and pass it through the Vega command line tools, then display the
resulting SVG in the `*vega*` buffer." t)
(register-definition-prefixes "vega-view" '("vega-view-"))

;;; End of scraped data

(provide 'vega-view-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vega-view-autoloads.el ends here
