;;; beancount-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from beancount.el

(add-to-list 'auto-mode-alist '("\\.beancount\\'" . beancount-mode))
(autoload 'beancount-mode "beancount" "\
A mode for Beancount files.

\\{beancount-mode-map}

(fn)" t)
(register-definition-prefixes "beancount" '("beancount-"))


;;; Generated autoloads from beancount-tests.el

(register-definition-prefixes "beancount-tests" '("beancount-"))


;;; Generated autoloads from flymake-bean-check.el

(autoload 'flymake-bean-check-enable "flymake-bean-check" "\
Enable checking via flymake." '(beancount-mode))
(register-definition-prefixes "flymake-bean-check" '("flymake-bean-check-"))

;;; End of scraped data

(provide 'beancount-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; beancount-autoloads.el ends here
