;;; markdown-soma-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from markdown-soma.el

(autoload 'markdown-soma-toggle-source-view "markdown-soma" "\
Toggle source view or FORCE on/off.

FORCE will expect a prefix positive integer to mean on or
negative prefix to mean off.

This will trigger markdown-soma-restart in an active session.

(fn FORCE)" t)
(autoload 'markdown-soma-restart "markdown-soma" "\
Restart a running soma session." t)
(register-definition-prefixes "markdown-soma" '("markdown-soma-"))

;;; End of scraped data

(provide 'markdown-soma-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; markdown-soma-autoloads.el ends here
