;;; toc-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from toc-mode.el

(autoload 'toc-gen-set-level "toc-mode" "\
Define the text properties of the heading level.
In a pdf-view buffer select a single word in the headline of a
certain level. Then run `toc-gen-set-level' to write the text
properties to the recipe.toml file that is created in the
document's directory. You will be prompted to enter the LEVEL
number. The highest level should have number 1, the next level
number 2 etc.

(fn LEVEL)" t)
(autoload 'toc-extract-pages "toc-mode" "\
Extract text from text layer of current document and cleanup.
Extract from STARTPAGE to ENDPAGE. Use with the universal
ARG (\\[universal-argument]) omits cleanup to get the unprocessed
text.

(fn ARG)" t)
(autoload 'toc-extract-pages-ocr "toc-mode" "\
Extract via OCR text of current document and cleanup.
Extract from STARTPAGE to ENDPAGE. Use with the universal
ARG (\\[universal-argument]) omits cleanup to get the
unprocessed text.

(fn ARG)" t)
(autoload 'toc-extract-outline "toc-mode" "\
Extract Table of Contents attached to current document." t)
(autoload 'toc-extract-only "toc-mode" "\
Just extract text via OCR without further processing.
Prompt for startpage and endpage and print OCR output to new buffer." t)
(register-definition-prefixes "toc-mode" '("toc-"))

;;; End of scraped data

(provide 'toc-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; toc-mode-autoloads.el ends here
