;;; org-page-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from op-enhance.el

(register-definition-prefixes "op-enhance" '("op/"))


;;; Generated autoloads from op-export.el

(register-definition-prefixes "op-export" '("op--post-hashtable" "op/"))


;;; Generated autoloads from op-git.el

(register-definition-prefixes "op-git" '("op/git-"))


;;; Generated autoloads from op-template.el

(register-definition-prefixes "op-template" '("op/"))


;;; Generated autoloads from op-util.el

(register-definition-prefixes "op-util" '("compare-standard-date" "con" "encode-string-to-url" "file-to-string" "fix-timestamp-string" "get-full-url" "string-" "trim-string"))


;;; Generated autoloads from op-vars.el

(register-definition-prefixes "op-vars" '("op/"))


;;; Generated autoloads from org-page.el

(register-definition-prefixes "org-page" '("op/" "org-page-version"))

;;; End of scraped data

(provide 'org-page-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-page-autoloads.el ends here
