;;; gnu-elpa-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gnu-elpa-maint.el

(register-definition-prefixes "gnu-elpa-maint" '("gnu-elpa--"))


;;; Generated autoloads from gnu-elpa-utils.el

 (eval-after-load 'package
  '(unless (assoc "gnu" package-archives)
     (push '("gnu" . "https://elpa.gnu.org/packages/")
           package-archives)))
 ;; Skip load-source-file-function which would slow us down by
 ;; a factor 2 (this assumes we were careful to save this file
 ;; so it doesn't need any decoding).
 (let ((load-source-file-function nil))
  (require 'gnu-elpa-features nil 'noerror))
(register-definition-prefixes "gnu-elpa-utils" '("gnu-elpa--"))

;;; End of scraped data

(provide 'gnu-elpa-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gnu-elpa-autoloads.el ends here
